### ISSUE TITLE
Permissions for protected map not working (bPermissions)

### ISSUE THREAD

**Issue by megge** [webbukkit/dynmap#1009]
Hi there,

I have a little problem concerning protected maps. Users (including me) have the permission node
- dynmap.map.towny.hd

but we can't see the map on the dynmap. The other maps work, though. You can take a look at it [here](http://rcom.dyndns-server.com/dynmap)

Part of the worldconfig

``` yaml
worlds:
  - name: towny
    title: "Towny"
    enabled: true
    hidestyle: air
    sendposition: true
    maps:
      - class: org.dynmap.hdmap.HDMap
        name: sd
        title: "SD Map"
        icon: images/block_flat.png
        perspective: default-sd
        shader: texturepack
        lighting: shadows-smooth
        image-format: jpg-q75
        protected: false
      - class: org.dynmap.hdmap.HDMap
        name: hd
        title: "HD Map"
        icon: images/block_flat.png
        perspective: default-hd
        shader: texturepack
        lighting: dn-bs
        image-format: jpg-q100
        protected: true
      - class: org.dynmap.hdmap.HDMap
        name: topo
        title: "Topological"
        icon: images/block_flat.png
        perspective: default-topo
        shader: topo-noplants
        lighting: default
        image-format: jpg-q75
        protected: false
```

[configuration.txt](http://pastebin.com/ANEndeLs)
Versions:
- git-Bukkit-1.3.2-R2.0-b2396jnks (MC: 1.3.2) (Implementing API version 1.3.2-R2.0)
- bPermissions v2.9.24
- dynmap v0.90-1347
- Dynmap-Towny v0.30
- Dynmap-WorldGuard v0.30
- VanishNoPacket v3.12.4

Can't think of any other related plugin, here is my full plugin list: bPermissions, Massband, FarmControl, Minequery, Craftconomy3, WorldEdit, NoCheatPlus, Buycraft, CommandBook, Vault, Multiverse-Core, CombatTag, Questioner, WorldGuard, BloodMoon, bChatManager, dynmap, HeroicDeathPlus, Dynmap-WorldGuard, MineBackup, CommandHelper, Turnstile, Gods, BKCommonLib, mcbans, VariableTriggers, ProtocolLib, Bankcraft, CleanroomGenerator, Jobs, WorldBorder, SWatchdog, MultiPack, Towny, Courier, Multiverse-Portals, Multiverse-Inventories, TagAPI, VanishNoPacket, Multiverse-NetherPortals, HomeSpawnPlus, NoLagg, ChestShop, Dynmap-Towny

I guess there is an issue with the permissions being cached (I had a similar problem with a protected world, which just worked after a while), but I can't access all of the source code :/
