### ISSUE TITLE
[SEVERE] Could not render: world 'netherworld' not defined in configuration.

### ISSUE THREAD

**Issue by tiramon** [webbukkit/dynmap#108]
20:01:36 [INFO] Loaded world: netherworld
20:01:36 [INFO] Loaded world: world
20:02:56 [SEVERE] Could not render: world 'netherworld' not defined in configuration.

'world' is rendered normaly 'netherworld' not

Configuration
# All paths in this configuration file are relative to Dynmap's data-folder: minecraft_server/plugins/dynmap/
# How often a tile gets rendered (in seconds).

renderinterval: 1

render-triggers:
- playermove
  #  - playerjoin
- blockplaced
- blockbreak
# The path where the tile-files are placed.

tilespath: web/tiles
# The path where the web-files are located.

webpath: web
# The network-interface the webserver will bind to (0.0.0.0 for all interfaces, 127.0.0.1 for only local access).

webserver-bindaddress: 0.0.0.0
# The TCP-port the webserver will listen on.

webserver-port: 8123
# Disables Webserver portion of Dynmap (Advanced users only)

disable-webserver: false
# Writes JSON to file in the webpath

jsonfile: false
# How often the json file gets written to(in seconds)

jsonfile-interval: 1
# The maptypes Dynmap will use to render.

worlds:
- name: world
  maps:
  - class: org.dynmap.flat.FlatMap
    prefix: flat
    colorscheme: default
  - class: org.dynmap.kzedmap.KzedMap
    renderers:
    - class: org.dynmap.kzedmap.DefaultTileRenderer
      prefix: t
      maximumheight: 127
      colorscheme: default
    - class: org.dynmap.kzedmap.CaveTileRenderer
      prefix: ct
      maximumheight: 127
- name: nether
  maps:
  - class: org.dynmap.flat.FlatMap
    prefix: flat
    colorscheme: default
  - class: org.dynmap.kzedmap.KzedMap
    renderers:
    - class: org.dynmap.kzedmap.DefaultTileRenderer
      prefix: nt
      maximumheight: 64
      colorscheme: default

web:
    # Handles the clientside updates differently only enable if using jsonfile
    jsonfile: false

```
# Interval the browser should poll for updates.
updaterate: 2000

showchatballoons: false
focuschatballoons: false

showchatwindow: false #true
allowwebchat: false #true
webchat-interval: 5
messagettl: 15

showplayerfacesonmap: false #true
showplayerfacesinmenu: false #true

joinmessage: "%playername% joined"
quitmessage: "%playername% quit"
spammessage: "You may only chat once every %interval% seconds."

components:
  - type: chat
  - type: chatballoon
    focuschatballoons: false
  - type: chatbox
    showplayerfaces: true
    messagettl: 5
  - type: playermarkers
    showplayerfaces: true
  #- type: digitalclock
  - type: timeofdayclock
    showdigitalclock: true

defaultworld: world
worlds:
  - title: World
    name: world
    maps:
      - type: KzedMapType
        title: Surface
        name: surface
        prefix: t
      - type: FlatMapType
        title: Flat
        name: flat
        prefix: flat
```
# \- type: KzedMapType
# title: Surface
# name: surface
# prefix: t
# \- type: KzedMapType
# title: Cave
# name: cave
# prefix: ct

```
  - title: Nether
    name: netherworld
    maps:
      - type: FlatMapType
        title: Flat
        name: flat
        prefix: flat
      - type: KzedMapType
        title: Surface
        name: nether
        prefix: nt
  # Example:
  #- title: Other World           # With what name the world is displayed.
  #  name: world_other            # The actual name of the world (equal to your directory-name).
  #  maps:
  #    - type: KzedMapType        # The type (or perspective) of the map. At the moment, there are no others than KzedMapType.
  #      title: Surface           # The name of the map that will be displayed.
  #      name: surface            # The actual name of the map (should be unique for this world).
  #      prefix: t                # The prefix of the tile-files that are generated.
  #      icon: images/block_other.png    # Sets a custom icon for the map. (optional)
  #    - type: KzedMapType
  #      title: Cave
  #      name: cave
  #      prefix: ct
```
# Enables debugging.
# debuggers:
# \- class: org.dynmap.debug.LogDebugger
