### ISSUE TITLE
Whitelist for which worlds dynmap should render

### ISSUE THREAD

**Issue by ingrimmm** [webbukkit/dynmap#1469]
From what I can tell there is no way to whitelist worlds so that dynmap will ONLY render those exact worlds. There's no easy way to "disable dynmap for all worlds except (world1, world2, world3...)" 

This would be extremely useful in cases like DimDoors and Mystcraft Ages where new dimensions are spawned all the time - there's no easy way (afaik) to tell Dynmap to ignore them without manually creating a new entries for each new dimension as it is created.

An example of whitelist configuration could be ... 

``` YAML
world-whitelist: true
     world: world
     world: DIM1
     world: DIM-1
```

and then all other worlds not explicity specified in the whitelist are ignored by Dynmap.
