### ISSUE TITLE
Using different map zoom-ins on same world messes everything up

### ISSUE THREAD

**Issue by xbenas** [webbukkit/dynmap#1789]
Using different map zoom-ins on same world messes everything up, like map does not update, web browser starts to lag and user positions do not update.
Seems to be client-side only.

Using

``` yaml
version: 0.24
#
# Default template for "Normal" environment worlds (deftemplatesuffix="vlowres")
#  Uses the HDMap renderer with view from the SE with the "vlowres" resolution (2 pixels per block edge)
#
#   This file MAY need to be replaced during an upgrade - rename file to 'custom-normal-vlowres.txt' if you wish to customize it
#
templates:
  # Template for normal world (HDMap vlowres)
  normal-vlowres:
    enabled: true
    # Number of extra zoom-out levels for world (each level is twice as big as the previous one)
    extrazoomout: 2
    title: "Earth"
    center:
      x: 0
      y: 64
      z: 0
    maps:
      - class: org.dynmap.hdmap.HDMap
        name: flat
        title: "2D"
        prefix: flat
        perspective: iso_S_90_vlowres
        shader: stdtexture
        lighting: nightandday
        # Adjust extra zoom in levels - default is 2
        mapzoomin: 5
      - class: org.dynmap.hdmap.HDMap
        name: surface
        title: "3D"
        prefix: t
        perspective: iso_SE_30_vlowres
        shader: stdtexture
        lighting: nightandday
        # Adjust extra zoom in levels - default is 2
        mapzoomin: 0
#      - class: org.dynmap.hdmap.HDMap
#        name: cave
#        title: "Cave"
#        prefix: ct
#       perspective: iso_SE_60_vlowres
#        shader: cave
#        lighting: default
#        # Adjust extra zoom in levels - default is 2
#        mapzoomin: 2
```

``` log4j
21:51:54 Dynmap version: core=2.2-SNAPSHOT-2044, plugin=2.2-SNAPSHOT-1106
21:51:56 This server is running CraftBukkit version git-Spigot-c5146ba-01930e2 (MC: 1.8.6) (Implementing API version 1.8.6-R0.1-SNAPSHOT)
```
