### ISSUE TITLE
Standard Coordinates for Webview

### ISSUE THREAD

**Issue by silelmot** [webbukkit/dynmap#1871]
i found settings for  zoom (defaultzoom) and map in the configuration.txt but where can is set the default coordinations for webview?

**Comment by Psy-Virus** [comment]
That's handled with the center switch in the custom template or world settings file you can create for each world.
It's like
```
center:
      x: 0
      y: 64
      z: 0
```
