### ISSUE TITLE
inhabitedTicks field not found - inhabited shader not functional

### ISSUE THREAD

**Issue by wtchappell** [webbukkit/dynmap#1881]
I'm getting this in my logs while attempting to use the inhabited shader - there are no other warnings or errors, and everything else with Dynmap besides inhabited is working fine.

```
inhabitedTicks field not found - inhabited shader not functional
```

 How do I configure something to actually add inhabitedTicks to my chunks?

custom-normal-hi_boost_xhi.txt snippet for inhabited:

``` yaml
- class: org.dynmap.hdmap.HDMap
   name: inhabited
   shader: inhabited
   lighting: default
   mapzoomin: 0
```
