### ISSUE TITLE
Moving a build with markers

### ISSUE THREAD

**Issue by frymaster** [webbukkit/dynmap#1900]
Hi,

I am doing a copy/paste of some builds in mcedit from our old world to our new one. For an entry in markers.yml of the form

```
            _sign_NE-2013_-906_61_-9962:
                icon: caution
                markup: true
                label: ''
                z: -9961.5
                world: NE-2013
                y: 61.5
                x: -905.5
```

am I correct that if I create an entry (while the server is off) in the new world like:

```
            _sign_NE-2016_10000_61_-5000:
                icon: caution
                markup: true
                label: ''
                z: -4999.5
                world: NE-2016
                y: 61.5
                x: 10000.5
```

then, assuming I got my x and z coords for the build in the new world correct, the signs shout Just Work(TM) and disappear when removed etc. as normal?

Is there a less intricate way to go about this?
