### ISSUE TITLE
Problem with "mapzoomin" and "mapzoomout"

### ISSUE THREAD

**Issue by Taybosquee** [webbukkit/dynmap#1907]
Using the following map settings will prevent you from zooming out (And change the zoom level the map loads with) but will not prevent you from zooming in. "mapzoomout" seems to not work or have no effect regardless of what you set it to. I may misunderstand how these two settings are meant to work, but my intent is to make the map a fixed zoom on load that can not be altered (As in no in or out zooming).

```
maps:
      - class: org.dynmap.hdmap.HDMap
        name: flat
        title: "2D"
        prefix: flat
        perspective: iso_S_90_lowres
        shader: stdtexture
        lighting: shadows
        mapzoomin: 1
        mapzoomout: 1
```
