### ISSUE TITLE
FullRender on large worlds breaking map

### ISSUE THREAD

**Issue by Cosmosis42** [webbukkit/dynmap#1986]
I have a very large world on my server, because the players tend to explore A LOT. When doing a full render, the map eventually gets so big that it seems to possibly overwrite other parts of the map? 

Basically, as it renders more of the map, older parts of the render seem to disappear.

**Comment by EvilOlaf** [comment]
Not sure but did you enable ` bigworld: true` for this map?

**Comment by Cosmosis42** [comment]
Isn't that automatically enabled for HDWorlds? Also, if not, how would I go about enabling it?

**Comment by EvilOlaf** [comment]
Add the option in your `worlds.txt` so it looks like this:

```
worlds:
-   name: world
    title: world
    enabled: true
    extrazoomout: 3
    maps:
    -   class: org.dynmap.hdmap.HDMap
        name: flat
        title: flat
        prefix: flat
        perspective: iso_S_90_lowres
        shader: stdtexture
        lighting: shadows
        mapzoomin: 2
    -   class: org.dynmap.hdmap.HDMap
        name: surface
        title: surface
        prefix: t
        perspective: iso_SE_30_lowres
        shader: stdtexture
        lighting: shadows
        mapzoomin: 2
    bigworld: true
```
