### ISSUE TITLE
[Add Wiki Page] Dynmap MySQL Setup

### ISSUE THREAD

**Issue by jwshields** [webbukkit/dynmap#2026]
I'd like to propose a Wiki page be added for setting up Dynmap with MySQL.

Instructions:
1. Download the MySQL jar file from this URL: http://dev.mysql.com/downloads/connector/j/
2. Unzip the downloaded file, rename the jar to 'mysql.jar' and move the file to '{minecraft base dir}/plugins/dynmap/mysql.jar'
3. Edit your configuration.txt to appear similar to code the below (for lines 18-35)
3.1. Edit the database hostname, port, database, username, password, prefix to your appropriate values
3.2. Normally `hostname: localhost` & `port: 3306` will not need to be changed
3.3. `database` is the name of the MySQL schema, depending on your setup you will want to change that
3.4. `prefix` is the text that gets applied to the names of the tables that Dynmap generates, useful if you only have one DB/Schema for your server
4. Start your Bukkit server and watch the magic happen

```
# Map storage scheme: only uncomment one 'type' value
#  filetree: classic and default scheme: tree of files, with all map data under the directory indicated by 'tilespath' setting
#  sqlite: single SQLite database file (this can get VERY BIG), located at 'dbfile' setting (default is file dynmap.db in data directory)
#  mysql: MySQL database, at hostname:port in database, accessed via userid with password
storage:
  # Filetree storage (standard tree of image files for maps)
  #type: filetree
  # SQLite db for map storage (uses dbfile as storage location)
  #type: sqlite
  #dbfile: dynmap.db
  # MySQL DB for map storage (at 'hostname':'port' in database 'database' using user 'userid' password 'password' and table prefix 'prefix'
  type: mysql
  hostname: localhost
  port: 3306
  database: [DB name]
  userid: [Username]
  password: [Password]
  prefix: ""
```
