### ISSUE TITLE
Lighting is always "shadows" in worlds configuration

### ISSUE THREAD

**Issue by SimonOrJ** [webbukkit/dynmap#2028]
Hello,

Whenever I try to change the `lighting` setting in the `worlds.txt` configuration file, the map still renders the tiles as `shadows` lighting preset.  I have been trying to get it working for hours until I gave up and declared it as a bug.

The End map used to render with the correct `brightnight` lighting, but it renders as if the dynmap is rendering daylight right now.

It used to work back when my server was using 1.8, but it seems to have stopped working properly since one of the updates in the middle.  My server is running latest Spigot of MC 1.11 and the latest snapshot of Dynmap (v2.4).

```yaml
    -   class: org.dynmap.hdmap.HDMap
        name: flat
        title: Flat
        prefix: flat
        perspective: iso_S_90_vlowres
        shader: stdtexture
        lighting: brightnight
        image-format: jpg-q90
        mapzoomin: 3
        mapzoomout: 3
        boostzoom: 0
        append_to_world: ''
        protected: false
```
![image](https://cloud.githubusercontent.com/assets/13530989/21000011/513f0af2-bce6-11e6-89b2-b179d53bd665.png)
