### ISSUE TITLE
How do I link Dynmap to a mysql server?

### ISSUE THREAD

**Issue by Sonic8608** [webbukkit/dynmap#2243]
I have followed the steps from another post of using a jar file, but then I got lost. I need help step by step to link my dynmap to xampp or something similar.

**Comment by triagonal** [comment]
You'll need to uncomment the lines concerning mysql in configuration.txt (you can view the default one [here](https://github.com/webbukkit/dynmap/blob/recommended/src/main/resources/configuration.txt)) under the storage heading.

Instead of the storage section looking like this:
```
storage:
  # Filetree storage (standard tree of image files for maps)
  type: filetree
  # SQLite db for map storage (uses dbfile as storage location)
  #type: sqlite
  #dbfile: dynmap.db
  # MySQL DB for map storage (at 'hostname':'port' in database 'database' using user 'userid' password 'password' and table prefix 'prefix'
  #type: mysql
  #hostname: localhost
  #port: 3306
  #database: dynmap
  #userid: dynmap
  #password: dynmap
  #prefix: ""
```

It should instead look like this:
```
storage:
  # Filetree storage (standard tree of image files for maps)
  # type: filetree
  # SQLite db for map storage (uses dbfile as storage location)
  #type: sqlite
  #dbfile: dynmap.db
  # MySQL DB for map storage (at 'hostname':'port' in database 'database' using user 'userid' password 'password' and table prefix 'prefix'
  type: mysql
  hostname: localhost
  port: 3306
  database: dynmap
  userid: dynmap
  password: dynmap
  prefix: ""
```
Remember to comment out the `type: filetree`, as only one storage type should be uncommented.
