### ISSUE TITLE
No night lighting on maps [with workaround]

### ISSUE THREAD

**Issue by kaonashi97** [webbukkit/dynmap#2248]
Hello,
I use Dynmap on my Spigot server and on my night map no night light is visible. It looks like a normal day light map.

Spigot: `CraftBukkit version git-Spigot-2086bb0-2f3ed3b (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)`
Dynmap: `2.5-Dev201706100405 - core version 2.5-Dev201706100401`

(If there is a newer version of dynmap, I didn't found on the known official channels.)

The map:
![image](https://user-images.githubusercontent.com/26349958/41868292-f2182ac6-78b5-11e8-95f8-6d6da005c1a0.png)

The config:
```yaml
    -   class: org.dynmap.hdmap.HDMap
        name: night
        title: Nachtsicht
        icon: images/block_night.png
        prefix: night
        perspective: iso_SE_30_lowres
        shader: stdtexture
        lighting: night
        image-format: default
        mapzoomin: 3
        mapzoomout: 3
        boostzoom: 2
        append_to_world: ''
        protected: false
```

The night map was not rendered until I changed the config `use-brightness-table` to `false` as written in #1725. This works for me as workaround and may even fix the most problems by others reported here with the night light but I'm unsure about the real problem.

With workaround:
![image](https://user-images.githubusercontent.com/26349958/41869234-a21403f8-78b8-11e8-8a4c-6673de9ad8a3.png)

I've tested around and added a flat map using the `shader: default` and `shader: stdtexture` and `lighting: brightnight` and `lighting: night` resulting in the same as the first one above. Seems to me as there is a problem with the brightness table config value or the data itself.
