### ISSUE TITLE
Water Problem

### ISSUE THREAD

**Issue by derPiepmatz** [webbukkit/dynmap#2258]
Is it possible that every water block is shown exactly the same?

**Comment by generrosity** [comment]
do you mean shader option for no_transparency ? Or setting the water alpha so that nothing is seen underneith?

**Comment by derPiepmatz** [comment]
for now the water on our dynmap: https://map.ansoria.de/ looks a bit strange, you see it better if your contrast is good on your screen and I dislike it, so it would be nice if I could somehow make it all look the same

**Comment by generrosity** [comment]
Thanks for sharing your map - it is really a piece of art 👍 

Yup - I can see the oddly orthogonal ravines.

What shader do you use? This describes how the default shader can ignore 'transparency': https://github.com/webbukkit/dynmap/wiki/Defining-custom-shaders

If youre using texture pack shader .... it doesn't list that 'transparency' is there, but it might be a trivial thing to try or request?

**Comment by derPiepmatz** [comment]
Currently our custom-shaders.txt looks like this:
```yaml
# The user is free to add new and custom shaders here, including replacements for standard ones
# Dynmap's install will not overwrite it
shaders:
-   class: org.dynmap.hdmap.TexturePackHDShader
    name: stdtexture
    texturepack: Conquest.zip
    better-grass: true
-   class: org.dynmap.hdmap.TopoHDShader
    name: topo
    color127: '#FFFFFF'
    color111: '#8B4513'
    color95: '#D2B48C'
    color79: '#FFFF00'
    color63: '#008000'
    color47: '#228B22'
    color38: '#0F1013'
    color31: '#0F1013'
    color15: '#0F1013'
    color0: '#0F1013'
    linecolor: '#000000'
    watercolor: '#0F1013'
    wateralpha: 0.1
-   class: org.dynmap.hdmap.DefaultHDShader
    name: defaultscheme
    colorscheme: default
    transparency: false
```
