### ISSUE TITLE
[Dynmap v2.6-beta-1 for Forge 1.12.2] - Black Tiles Twilight Forest

### ISSUE THREAD

**Issue by Misteralex007** [webbukkit/dynmap#2263]
Hi !

In the documentation, the Twilight Forest are supported mods but I only get black tiles.
I don't know if I need to change configuraiton file "world.txt".

This is the configuration file, if some one knows how to fix that ?

``` 
worlds: 
  - name: "Biome Bundle"
    title: "Biome Bundle"
    enabled: true
    sendhealth: true
    sendposition: true
    bigworld: true
    extrazoomout: 3
    maps: 
      - class: org.dynmap.hdmap.HDMap
        lighting: shadows
        mapzoomin: 0
        name: flat
        perspective: iso_S_90_vlowres
        prefix: flat
        shader: stdtexture
        title: Flat
      - class: org.dynmap.hdmap.HDMap
        name: surface
        title: "Surface"
        prefix: t
        perspective: iso_SE_30_vlowres
        shader: stdtexture
        lighting: shadows
        mapzoomin: 0
  - name: DIM-1
    sendhealth: true
    sendposition: true
    title: Nether
    bigworld: true
    enabled: true
    maps: 
      - class: org.dynmap.hdmap.HDMap
        lighting: nethershadows
        mapzoomin: 2
        name: flat
        perspective: iso_S_90_vlowres
        prefix: flat
        shader: stdtexture
        title: Flat
  - name: DIM1
    sendhealth: true
    sendposition: true
    title: "The End"
    bigworld: true
    enabled: true
    maps: 
      - class: org.dynmap.hdmap.HDMap
        lighting: brightnight
        mapzoomin: 0
        name: flat
        perspective: iso_S_90_vlowres
        prefix: flat
        shader: stdtexture
        title: Flat
  - name: DIM7
    sendhealth: true
    sendposition: true
    title: "Twilight Forest"
    bigworld: true
    enabled: true
    extrazoomout: 3
    maps: 
      - class: org.dynmap.hdmap.HDMap
        lighting: shadows
        mapzoomin: 0
        name: flat
        perspective: iso_S_90_vlowres
        prefix: flat
        shader: stdtexture
        title: Flat
      - class: org.dynmap.hdmap.HDMap
        name: surface
        title: "Surface"
        prefix: t
        perspective: iso_SE_30_vlowres
        shader: stdtexture
        lighting: shadows
        mapzoomin: 0
```
