### ISSUE TITLE
Multiple maps show at the same time (pre-1.13)

### ISSUE THREAD

**Issue by MarcoStuurman** [webbukkit/dynmap#2293]
Hi,

I use the following map config:
```
templates:
  # Template for normal world (HDMap hires)
  normal-hires:
    enabled: true
    # Number of extra zoom-out levels for world (each level is twice as big as the previous one)
    extrazoomout: 1
    #center:
    #  x: 0
    #  y: 64
    #  z: 0
    maps:
      - class: org.dynmap.hdmap.HDMap
        name: flat
        title: "Flat"
        prefix: flat
        perspective: iso_S_90_lowres
        shader: stdtexture
        lighting: shadows
        mapzoomin: 1
      - class: org.dynmap.hdmap.HDMap
        name: surfacese
        title: "Surface ZuidOost"
        prefix: t
        perspective: iso_SE_30_hires
        shader: stdtexture
        lighting: shadows
        mapzoomin: 1
      - class: org.dynmap.hdmap.HDMap
        name: surfacenw
        title: "Surface NoordWest"
        prefix: t
        perspective: iso_NW_30_hires
        shader: stdtexture
        lighting: shadows
        mapzoomin: 1
      - class: org.dynmap.hdmap.HDMap
        name: surfacene
        title: "Surface NoordOost"
        prefix: t
        perspective: iso_NE_30_hires
        shader: stdtexture
        lighting: shadows
        mapzoomin: 1
      - class: org.dynmap.hdmap.HDMap
        name: surfacesw
        title: "Surface ZuidWest"
        prefix: t
        perspective: iso_SW_30_hires
        shader: stdtexture
        lighting: shadows
        mapzoomin: 1
```

which shows

https://fe.ax/1534672630-8323b261624e5f75f5c84b1321eb92d1.20180819115710.png

Have I misconfigured the plugin or is this a newly introduced bug? I've rendered with dynmap radiusrender 1000

Thank you
