### ISSUE TITLE
Chunks rendering outside of visibility limits

### ISSUE THREAD

**Issue by DefinePvP** [webbukkit/dynmap#2294]
I have set the visibility limits to 8,000; however when I teleport outside of 8,000 and place blocks, they still generate tiles on the dynmap.
configuration.txt: https://pastebin.com/0AG5i6Ri
world.txt: https://pastebin.com/Sy0uxZsx

**Comment by TomSputz** [comment]
The `- name: world` bit is important - the `visibilitylimits` setting is a property of a world, so you have to make sure it is a child of the world you want to edit e.g.

```
worlds: 
  - 
    name: world
    title: Overworld
    enabled: true
    fullrenderlocations: 
      - 
        x: -84
        y: 64
        z: 256
    visibilitylimits: 
      - 
        r: 300
        x: -84
        z: 256
    hidestyle: air
    maps: 
      - 
        class: org.dynmap.hdmap.HDMap
        icon: images/block_biome.png
        lighting: brightnightandday
        mapzoomin: 2
        mapzoomout: 3
        name: persp
        perspective: iso_SE_30_hires
        prefix: persp
        title: Perspective
```
And by the way - `fullrenderlocations` are the coordinates you want dynmap to start rendering the map when you run `/dynmap fullrender [world]`, so you dont really need two of them - just set it to the center of your world
