### ISSUE TITLE
Layer order

### ISSUE THREAD

**Issue by SlimeDog** [webbukkit/dynmap#2349]
Spigot 1.13.1
Dynmap 3.0-beta-1-129

Following the wiki, I tried to configure player markers layer on top. I set
```
  - class: org.dynmap.ClientComponent
    type: playermarkers
    showplayerfaces: true
    showplayerhealth: false
    # If true, show player body too (only valid if showplayerfaces=true
    showplayerbody: false
    # Option to make player faces small - don't use with showplayerhealth
    smallplayerfaces: true
    # Optional - make player faces layer hidden by default
    hidebydefault: false
    # Optional - ordering priority in layer menu (low goes before high - default is 0)
    layerprio: -1
    # Optional - label for player marker layer (default is 'Players')
    label: "Players"
```
but player markers remain below the other layers. Should that work, or do I need to leave that layerprio:0 and set the other layers to layerprio to values greater than 0 ?

What have I missed?

**Comment by generrosity** [comment]
Likely doesn't work with a negative. Have you indeed tried with other layers at higher values?

**Comment by SlimeDog** [comment]
I don't see how to set the layer priorities. The wiki mentions prio but the configuration files (markers.yml and configuration.txt) show layerprio (as above). Nothing I change them to seems to change the displayed priorities.

**Comment by SlimeDog** [comment]
```
>dmarker listsets
[16:37:53 INFO]: BiomeTour: label:"BiomeTour", hide:false, prio:0, deficon:default
[16:37:53 INFO]: Citizens2: label:"NPCs", hide:false, prio:0, deficon:default
[16:37:53 INFO]: essentials.homes: label:"Homes", hide:false, prio:20, deficon:default
[16:37:53 INFO]: essentials.warps: label:"Warps", hide:false, prio:21, deficon:default
[16:37:53 INFO]: markers: label:"Markers", hide:false, prio:0, deficon:default
[16:37:53 INFO]: structures: label:"Structures", hide:false, prio:10, deficon:default
[16:37:53 INFO]: worldguard.markerset: label:"WorldGuard", hide:false, prio:0, deficon:default
```
I don't see players at all, unless they are included in Markers. If so, then configuration.txt:
```
components:
...
  - class: org.dynmap.ClientComponent
    type: playermarkers
    showplayerfaces: true
    showplayerhealth: false
    # If true, show player body too (only valid if showplayerfaces=true
    showplayerbody: false
    # Option to make player faces small - don't use with showplayerhealth
    smallplayerfaces: true
    # Optional - make player faces layer hidden by default
    hidebydefault: false
    # Optional - ordering priority in layer menu (low goes before high - default is 0)
    layerprio: 0
    # Optional - label for player marker layer (default is 'Players')
    label: "Players"
```

Players layer is shown on the map, but it is underneath other layers (for example, homes).
