### ISSUE TITLE
Angle of view problem when defining surface map of 32 scale

### ISSUE THREAD

**Issue by Cubox-** [webbukkit/dynmap#2373]
Hi,

I am having an issue where the generated surface map is not of the right angle, despite having the only difference between it and the default surface it's scale.

Here are screenshots comparing the two resulting views (normal first, then custom):

![Standard surface map](https://user-images.githubusercontent.com/479129/47958862-c79fce80-dfd4-11e8-9395-039972eeb2cb.png)

![Custom surface map](https://user-images.githubusercontent.com/479129/47958895-73e1b500-dfd5-11e8-994f-836aa15f930b.png)

Here is the template I am using:

```
version: 0.20
templates:
  normal-cubox:
    enabled: true
    extrazoomout: 2
    maps:
      - class: org.dynmap.hdmap.HDMap
        name: surface
        title: "Surface"
        prefix: t
        perspective: iso_SE_30_hires
        shader: stdtexture
        lighting: shadows
        mapzoomin: 5
      - class: org.dynmap.hdmap.HDMap
        name: surfacehd
        title: "Surface HD"
        prefix: thd
        perspective: iso_SE_30_vhires
        shader: stdtexture
        lighting: shadows
        mapzoomin: 5
```

Here are the perspectives definitions:

```
  - class: org.dynmap.hdmap.IsoHDPerspective
    name: iso_SE_30_hires
    azimuth: 135
    inclination: 30
    scale: 16

  - class: org.dynmap.hdmap.IsoHDPerspective
    name: iso_SE_30_vhires
    azimuth: 135
    inclinaison: 30
    scale: 32
```

Since I cannot see what I did wrong, I am assuming this is either a problem with the plugin, or that changing the scale changes the angle. However, I had the same "bugged" angle at 32 or 64 scale.

Any help would be greatly appreciated. You can check the map itself at [(http://a.cubox.me:8123/](http://a.cubox.me:8123/) if you wish.
