### ISSUE TITLE
Dynmap renders water with a  dark blue tone strongly different from the original resourcepack since update

### ISSUE THREAD

**Issue by WELTEINZ** [webbukkit/dynmap#2382]
Hi,

since the update on Dynmap v3.0-beta-2 the color of the original **water** texture in any resource pack I tested is strongly changed during rendering. I have tested several 1.13.2 packs (e.g. joliecraft). Changes in the shader.txt à la..

```
shaders:
-   class: org.dynmap.hdmap.TexturePackHDShader
    name: stdtexture
    texturepack: joliecraft.zip
    watercolor: '#1A4d6B'
    #hiddenids:
    #- 56
```

..do not lead to the desired goal.

![2018-11-14 16_31_15-map - welteinz](https://user-images.githubusercontent.com/44711940/48493813-eb60e100-e82c-11e8-9b31-d6d7fc87a70b.png)

There may be something wrong with these settings or the functions behind it..
```
#  use-generated-textures: if true, use generated textures (same as client); false is static water/lava textures
#  correct-water-lighting: if true, use corrected water lighting (same as client); false is legacy water (darker)
#  transparent-leaves: if true, leaves are transparent (lighting-wise): false is needed for some Spout versions that break lighting on leaf blocks
use-generated-textures: true
correct-water-lighting: true
transparent-leaves: true
```
My settings are:
Fedora 29
8 GB RAM and 4 Cores for a guest of an Intel Xeon X5690 in a KVM environment.

MC:
PaperMC dev 417

Plugins:
DiscordSRV 1.16.4
Dynmap v3.0-beta-2

[Our Map](https://map.welteinz.de)

**Is this a bug?**

Thanks for help in advance!
