### ISSUE TITLE
DynMap shows just stone.

### ISSUE THREAD

**Issue by Jaffaaaa** [webbukkit/dynmap#2384]
I'm been trying out the worlds.txt and tried these settings: https://pastebin.com/Wz82353t

But it just ends up looking like this: https://cdn.discordapp.com/attachments/511143654841122817/513264892715859969/b40ba9722fda16aa3ee6875985d6c51a.png

I'm trying to get a look similar to: https://map.wynncraft.com

**Comment by Crysalix** [comment]
Remove this from your settings.

```
    hiddenlimits:
      - x0: 2047
        z0: 2047
        x1: -1919
        z1: -1919
```
