### ISSUE TITLE
Blank black page - /standalone/config.js not found

### ISSUE THREAD

**Issue by Foxtrek64** [webbukkit/dynmap#2445]
## Server Information

- I can reproduce this issue consistently
     - [ ] In Multiplayer 
     - [x] After deleting/renaming the DYNMAP folder
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- I have tried the following diagnostics;
     - [ ] Re-rendered missing chunks using /dynmap fullrender
     - [x] Cleared cached tiles using /dynmap purgeworld [world] (especially if using a map from an older version)
     - [x] Deleted/Renamed the dynmap folder to regenerate configs and files fresh
     - [ ] Tested using the 'HEAD' version from dynmap.us/builds (these are stable to use)
     - [x] Rechecked the Minecraft Server and Webserver Config (If using an external Webserver)

## Issue Description
Navigating to [my dynmap site](https://dynmap.ravenrockrp.com) shows a black screen. Opening the firefox dev tools reveals that it failed to find `/standalone/config.js`. Browsing the file system confirms this does not exist.

## Reproduce Steps
1. Create directory `/var/www/dynmap2`, `chown www-data:www-data dynmap2/` `chmod 775 dynmap2/`
1. Create a virtual host following this [DigitalOcean Guide](https://www.digitalocean.com/community/tutorials/how-to-set-up-apache-virtual-hosts-on-ubuntu-14-04-lts)
1. Configure HTTPS and confirm site is functioning properly with dummy index.html
1. Delete dummy index.html, copy files from `server/dynmap/web` into `/var/www/dynmap2`
1. Edit `server/dynmap/configuration.txt`
    1. Disable `org.dynmap.InternalClientUpgradeComponent`
    1. Enable `org.dynmap.JsonFileClientUpdateComponent`
    1. Set `tilespath: /var/www/dynmap2/tiles`
    1. Set `webpath: /var/www/dynmap2`
    1. Set `disable-webserver: true`
1. With server running, navigate to dynmap address

## Additional Information

I've read through #2254, which lead me to try modifying this section of `configuration.txt`
```yaml
url:
    # configuration URL
    #configuration: "up/configuration"
    configuration: 'standalone/dynmap_config.json?={timestamp}'
    # update URL
    #update: "up/world/{world}/{timestamp}"
    update: 'standalone/dynmap_{world}.json?={timestamp}'
    # sendmessage URL
    #sendmessage: "up/sendmessage"
    sendmessage: 'standalone/sendmessage.php'
    # login URL
    #login: "up/login"
    login: 'standalone/login.php'
    # register URL
    #register: "up/register"
    register: 'standalone/register.php'
    # tiles base URL
    #tiles: "tiles/"
    tiles: 'tiles/'
    # markers base URL
    #markers: "tiles/"
    markers: 'tiles/'
    # Snapshot cache size, in chunks
```
However, this did not seem to have any result. Additionally, it should be noted that this is `dynmap2` because `/var/www/dynmap` is the directory for the dynmap on my Paper server, which is working correctly using this same methodology, albeit running a different version. Access to that has been disabled as I took over the `dynmap` host name from that site and transferred it to my SpongeForge server (simply by modifying the virtual host file for http and https).

This is quite possibly the same issue as in #2126, and like the OP in that thread, I can confirm write access.
```
root@lfrp01:/var/www/dynmap2# ls -lah
total 64K
drwxrwxr-x 7 www-data www-data 4.0K Feb 14 05:11 .
drwxr-xr-x 6 root     root     4.0K Feb 14 05:11 ..
-rwxrwxr-x 1 www-data www-data  109 Feb 14 05:09 config.js
drwxrwxr-x 3 www-data www-data 4.0K Feb 14 05:09 css
-rwxrwxr-x 1 www-data www-data  369 Feb 14 05:09 gettiles.php
drwxrwxr-x 2 www-data www-data 4.0K Feb 14 05:09 images
-rwxrwxr-x 1 www-data www-data  323 Feb 14 05:09 inactive.html
-rwxrwxr-x 1 www-data www-data 2.5K Feb 14 05:09 index.html
drwxrwxr-x 2 www-data www-data 4.0K Feb 14 05:09 js
-rwxrwxr-x 1 www-data www-data 3.6K Feb 14 05:09 login.html
-rwxrwxr-x 1 www-data www-data  105 Feb 14 05:09 robots.txt
drwxrwxr-x 2 www-data www-data 4.0K Feb 14 05:59 standalone
drwxrwxr-x 5 www-data www-data 4.0K Feb 14 05:48 tiles
-rwxrwxr-x 1 www-data www-data 1.3K Feb 14 05:09 up.aspx
-rwxrwxr-x 1 www-data www-data 1.6K Feb 14 05:09 up.php
-rwxrwxr-x 1 www-data www-data   39 Feb 14 05:09 version.js
root@lfrp01:/var/www/dynmap2# groups mc2
mc2 : mc2 www-data
```
The `mc2` account was auto-created by Multicraft and is the user and context under which the server is running, as seen here (incomplete listing, but this piece is working correctly):
```
root@lfrp01:/var/www/dynmap2/tiles/_markers_# ls -lah
total 356K
drwxrwxr-x 2 www-data www-data 4.0K Feb 14 05:39 .
drwxrwxr-x 5 www-data www-data 4.0K Feb 14 05:48 ..
-rw-rw---- 1 mc2      mc2       831 Feb 14 05:39 anchor.png
-rw-rw---- 1 mc2      mc2       771 Feb 14 05:39 bank.png
-rw-rw---- 1 mc2      mc2       639 Feb 14 05:39 basket.png
-rw-rw---- 1 mc2      mc2      1.5K Feb 14 05:39 bed.png
-rw-rw---- 1 mc2      mc2       609 Feb 14 05:39 beer.png
-rw-rw---- 1 mc2      mc2       756 Feb 14 05:39 bighouse.png
-rw-rw---- 1 mc2      mc2       726 Feb 14 05:39 blueflag.png
-rw-rw---- 1 mc2      mc2       871 Feb 14 05:39 bomb.png
-rw-rw---- 1 mc2      mc2       719 Feb 14 05:39 bookshelf.png
-rw-rw---- 1 mc2      mc2       959 Feb 14 05:39 bricks.png
-rw-rw---- 1 mc2      mc2       657 Feb 14 05:39 bronzemedal.png
-rw-rw---- 1 mc2      mc2       692 Feb 14 05:39 bronzestar.png
-rw-rw---- 1 mc2      mc2       630 Feb 14 05:39 building.png
-rw-rw---- 1 mc2      mc2       792 Feb 14 05:39 cake.png
-rw-rw---- 1 mc2      mc2       729 Feb 14 05:39 camera.png
...
```
