### ISSUE TITLE
Dynmap full render is rendering lighting in tiles as black patches.

### ISSUE THREAD

**Issue by mibby** [webbukkit/dynmap#2569]
Paper dev 148 (Spigot 1.14.4)
dynmap v3.0-beta-5-218

@mikeprimm Dynmap seems to be rendering already generated chunks with black patchy lighting with a fullrender task. Possibly an issue with loading chunks prematurely?

Edit: Seems to only render these broken shadows on chunks older than 1.14. Once my map got to 1.14 chunks in the outer perimeter, everything started to look fine. The inner chunks were generated in 1.12, updated to 1.13 with the spigot upgrade parameter, then updated again to 1.14 with the upgrade parameter. 
![link](https://i.imgur.com/wmtiyPN.jpg)

I stopped the full render after I noticed it was generating blotchy shadows.

Going to the area manually and doing a radiusrender fixes the lighting on the rendered tiles. These chunks are already pre-generated and were already rendered a long time ago fine, I'm doing another full render on top to force the entire map to update all tiles that may have had changes and to render the expanded world (pre-generated) for 1.14. The chunks in-game don't seem to have any broken lighting issues.

Config
https://paste.ubuntu.com/p/QzwFnyGK6f/

```
worlds:
-   name: world
    title: Overworld
    extrazoomout: 1
    center:
        x: 0.5
        y: 64.0
        z: 0.5
    maps:
    -   class: org.dynmap.hdmap.HDMap
        name: surface
        title: Surface
        prefix: surface
        perspective: iso_SE_30_medres
        shader: stdtexture
        lighting: shadows-smooth
        mapzoomin: 1
```
