### ISSUE TITLE
The lit-cave appears not to work

### ISSUE THREAD

**Issue by gjvnq** [webbukkit/dynmap#2591]
Hi, it seems that the `lit-cave` option is not working.

`worlds.txt`:

```
   - class: org.dynmap.hdmap.HDMap
      name: cave
      title: "Subterrâneo"
      prefix: cave
      perspective: iso_NW_30_medres
      shader: lit-cave
```

`shaders.txt`:

```
  # Cave view shader - only lit caves
  - class: org.dynmap.hdmap.CaveHDShader
    name: lit-cave
    onlyiflit: true
```

![Captura de Tela 2019-08-21 às 14 42 56](https://user-images.githubusercontent.com/3050524/63454893-0c8cd880-c422-11e9-8f26-47b9247cce10.png)

**Comment by aSemy** [comment]
A late reply, but I think this is working for me. My guess is that the caves are illuminated by lava. It would be nice to have only artificial lighting showing on Dynmap.

Here's some screenshots of Dynmap looking at the same location.

Isometric view:

```yml
    -   class: org.dynmap.hdmap.HDMap
        name: surface
        title: Surface
        prefix: t
        perspective: iso_SE_30_hires
        shader: stdtexture
        lighting: shadows-smooth
        mapzoomin: 1
```

![image](https://user-images.githubusercontent.com/897017/77808562-26635d80-708c-11ea-85fd-3fe129a876f5.png)

Cave render:

```yml
    -   class: org.dynmap.hdmap.HDMap
        name: cave
        title: Cave
        prefix: ct
        perspective: iso_SE_60_lowres
        shader: cave-noplants
        lighting: default
        mapzoomin: 3
```

![image](https://user-images.githubusercontent.com/897017/77808570-31b68900-708c-11ea-9c91-501fd2b0d9b9.png)

Lit cave render:

```yml
    -   class: org.dynmap.hdmap.HDMap
        name: cave_lit
        title: "Cave (lit)"
        prefix: nct
        perspective: iso_SE_60_lowres
        shader: lit-cave-noplants
        mapzoomin: 3
        lighting: default
```

![image](https://user-images.githubusercontent.com/897017/77808574-38dd9700-708c-11ea-8a56-2b926ebe8cba.png)
