### ISSUE TITLE
Option to divide one large world into multiple small section

### ISSUE THREAD

**Issue by Ice-Drake** [webbukkit/dynmap#2626]
Using dynmap version 3.0b5 on Spigot version 1.14.3, I tried the following configuration below, and I only got two separate (and very distant) rendered sections instead of two separate views of the same world. Is there a way to shorten them or split their views into something like two separate worlds?
```
 - name: world
    title: "World (Area 1)"
    enabled: true
    visibilitylimits:
      - x0: -650
        z0: -400
        x1: 450
        z1: 700

  - name: world
    title: "World (Area 2)"
    enabled: true
    visibilitylimits:
      - x0: -43250
        z0: 16900
        x1: -42750
        z1: 17400
```
