### ISSUE TITLE
Get “unable to write” error messages

### ISSUE THREAD

**Issue by xZise** [webbukkit/dynmap#282]
Hello,
I'm getting `09:10:41 [INFO] [dynmap] Image file plugins/dynmap/web/tiles/world/f/0_-3/zz_16_-80.png - unable to write - retry #3` with various files and I don't know what is wrong. I already removed at least 10 GiB so, not enough free space isn't possible.

I'm testing the HD Render with following file: `dynmap-0.20-bin.zip 13-Jul-2011 08:08` with CraftBukkit 978.

``` yaml
# All paths in this configuration file are relative to Dynmap's data-folder: minecraft_server/plugins/dynmap/
# NOTE: this is a sample of the standard configuration.txt, with HDMap renders substituted

components:
  - class: org.dynmap.ClientConfigurationComponent

  - class: org.dynmap.InternalClientUpdateComponent
    sendhealth: true
    sendposition: true
    allowwebchat: true
    webchat-interval: 5
    hidewebchatip: false
    trustclientname: false
  #- class: org.dynmap.JsonFileClientUpdateComponent
  #  writeinterval: 1
  #  sendhealth: true
  #  sendposition: true
  #  allowwebchat: false
  #  hidewebchatip: false

  #- class: org.dynmap.SimpleWebChatComponent
  #  allowchat: true
  - class: org.dynmap.herochat.HeroWebChatComponent
    # Control which HeroChat channel messages from web are directed to 
    herochatwebchannel: dynmap
    # Control which channels are monitored and reported to the web
    herochatchannels:
      - dynmap

  - class: org.dynmap.ClientComponent
    type: chat
#  - class: org.dynmap.ClientComponent
#    type: chatballoon
#    focuschatballoons: false
  - class: org.dynmap.ClientComponent
    type: chatbox
    showplayerfaces: true
    messagettl: 5
  - class: org.dynmap.ClientComponent
    type: playermarkers
    showplayerfaces: true
    showplayerhealth: true
  #- class: org.dynmap.ClientComponent
  #  type: digitalclock
  - class: org.dynmap.ClientComponent
    type: timeofdayclock
    showdigitalclock: true
    showweather: true
  #- class: org.dynmap.regions.RegionsComponent
  #  type: regions
  #  name: WorldGuard
  #  useworldpath: true
  #  filename: regions.yml
  #  basenode: regions
  #  use3dregions: true
  #  infowindow: '<div class="infowindow"><span style="font-size:120%;">%regionname% - %priority% (%parent%)</span><br /> Owners <span style="font-weight:bold;">%playerowners% %groupowners%</span><br />Members <span style="font-weight:bold;">%playermembers% %groupmembers%</span><br />Flags<br /><span style="font-weight:bold;">%flags%</span></div>'
  #  regionstyle:
  #    strokeColor: "#FF0000"
  #    strokeOpacity: 0.8
  #    strokeWeight: 3
  #    fillColor: "#FF0000"
  #    fillOpacity: 0.35
  #  # Optional setting to limit which regions to show, by name - if commented out, all regions are shown
  #  visibleregions:
  #    - homebase
  #    - miningsite
  #- class: org.dynmap.TestComponent
  #  stuff: "This is some configuration-value"

# Treat hiddenplayers.txt as a whitelist for players to be shown on the map? (Default false)
display-whitelist: false

# How often a tile gets rendered (in seconds).
renderinterval: 1

# Zoom-out tile update period - how often to scan for and process tile updates into zoom-out tiles (in seconds)
zoomoutperiod: 60

# Tile hashing is used to minimize tile file updates when no changes have occurred - set to false to disable
enabletilehash: true

render-triggers:
  #- chunkloaded
  #- playermove
  #- playerjoin
  - blockplaced
  - blockbreak
  - snowform
  - leavesdecay
  - blockburn
  - chunkgenerated

# The path where the tile-files are placed.
tilespath: web/tiles

# The path where the web-files are located.
webpath: web

# The network-interface the webserver will bind to (0.0.0.0 for all interfaces, 127.0.0.1 for only local access).
webserver-bindaddress: 0.0.0.0

# The TCP-port the webserver will listen on.
webserver-port: 8028

# Disables Webserver portion of Dynmap (Advanced users only)
disable-webserver: false

# Enable/disable having the web server allow symbolic links (true=compatible with existing code, false=more secure (default))
allow-symlinks: true

# Period between tile renders for fullrender, in seconds (non-zero to pace fullrenders, lessen CPU load)
timesliceinterval: 0.5

# Maximum chunk loads per server tick (1/20th of a second) - reducing this below 90 will impact render performance, but also will reduce server thread load
maxchunkspertick: 200

# Interval the browser should poll for updates.
updaterate: 2000

showplayerfacesinmenu: true

# Set sidebaropened: true to pin menu sidebar opened
#sidebaropened: true

joinmessage: "%playername% joined"
quitmessage: "%playername% quit"
spammessage: "You may only chat once every %interval% seconds."
webprefix: "§2[WEB] "
websuffix: "§f"

defaultzoom: 0
defaultworld: world

# template world - this is used for worlds that exist but aren't defined in the worlds section.
# Also, it supplies the "maps" section for worlds lacking a maps section, and the "center"
# for worlds lacking a "center" section.
templates:
  # Template for normal world
  normal:
    enabled: true
    # If bigworld set to true, use alternate directory layout better suited to large worlds
    bigworld: true
    # Number of extra zoom-out levels for world (each level is twice as big as the previous one)
    extrazoomout: 2
    center:
      x: 0
      y: 64
      z: 0
    maps:
      - class: org.dynmap.hdmap.HDMap
        name: flat
        title: "Flat"
        prefix: f
        perspective: iso_S_90_medres
        shader: default
  #      lighting: default
  #      # To render a world as a "night view", switch to lighting: night
  #      lighting: night
        # To render both night and day versions of tiles, set light: nightandday
        lighting: nightandday
  #      # Background color for map during the day
  #      backgroundday: "#153E7E"
  #      # Background color for map during the night
  #      backgroundnight: "#000000"        
  #      # Background color for map (independent of night/day)
  #      background: "#000000"
      - class: org.dynmap.hdmap.HDMap
        name: surface
        title: "Surface"
        prefix: s
        perspective: iso_SE_60_medres
        shader: default
  #      lighting: default
  #      # Add shadows to world (based on top-down shadows from chunk data)
  #      lighting: shadows
  #      # To render a world as a "night view", set lighting: night
  #      lighting: night
        # To render both night and day versions of tiles, set lighting: nightandday
        lighting: nightandday
  #      # Background color for map during the day
  #      backgroundday: "#153E7E"
  #      # Background color for map during the night
  #      backgroundnight: "#000000"        
  #      # Background color for map (independent of night/day)
  #      background: "#000000"
  #      # Sets the icon to 'images/block_custom.png'
  #      icon: custom
  #      # Biome-based mapping
      - class: org.dynmap.hdmap.HDMap
        name: biome
        title: "Biome"
        prefix: b
        perspective: iso_SE_60_medres
        lighting: default
        # Biome-based shading : biome=biome type, temperature=biome-temperature, rainfall=biome-rainfall
        shader: biome
      - class: org.dynmap.hdmap.HDMap
        name: cave
        title: "Cave"
        prefix: c
        perspective: iso_SE_60_medres
        shader: cave
        lighting: default

  # Nether world template
  nether:
    enabled: true
  #  # If bigworld set to true, use alternate directory layout better suited to large worlds
  #  bigworld: true
  #  # Number of extra zoom-out levels for world (each level is twice as big as the previous one)
  #  extrazoomout: 3
    center:
      x: 0
      y: 64
      z: 0
    maps:
      - class: org.dynmap.hdmap.HDMap
        name: flat
        title: "Flat"
        prefix: flat
        perspective: iso_S_90_lowres
        shader: default
        lighting: default
        # Map background color (day or night)
        background: "#300806"
      - class: org.dynmap.hdmap.HDMap
        name: nether
        title: "Surface"
        prefix: nt
        perspective: iso_SE_60_lowres
        shader: default
        lighting: default
        # Map background color (day or night)
        background: "#300806"
  # Skylands world template
  skylands:
    enabled: true
  #  # If bigworld set to true, use alternate directory layout better suited to large worlds
  #  bigworld: true
  #  # Number of extra zoom-out levels for world (each level is twice as big as the previous one)
  #  extrazoomout: 3
    center:
      x: 0
      y: 64
      z: 0
    maps:
      - class: org.dynmap.hdmap.HDMap
        name: flat
        title: "Flat"
        prefix: flat
        perspective: iso_S_90_lowres
        shader: default
        lighting: default
        # Background color for map during the day
        backgroundday: "#153E7E"
        # Background color for map during the night
        backgroundnight: "#000000"        
      - class: org.dynmap.hdmap.HDMap
        name: skylands
        title: "Surface"
        prefix: st
        perspective: iso_SE_60_lowres
        shader: default
        lighting: nightandday
        # Background color for map during the day
        backgroundday: "#153E7E"
        # Background color for map during the night
        backgroundnight: "#000000"        

# The maptypes Dynmap will use to render.
worlds:
  - name: world
    title: "World"
  - name: nether
    title: "Nëther"
  - name: exp
    title: "Experimental"
    enabled: false #As this world doesn't exists
  # Worlds can be handled by templates, based on world type
  # You can override the properties of the template by specifying them in this section
  #    for example 'Title: "My Awesome World"'
  #- name: world
  #  title: "World"
  #   Use 'enabled: false' to disable a certain world.
  #  enabled: false
  #   Use sendposition: false to prevent player positions from showing when on this world (if sendposition is globally enabled)
  #  sendposition: false
  #   Use sendhealth: false ot prevent player health from showing when on this world (if sendhealth is globally enabled)
  #  sendhealth: false
  #  # If world isn't contiguous chunks (due to teleporting, for example), fullrender needs to be given other locations to scan for tiles on each patch of chunks
  #  fullrenderlocations:
  #    - x: 10000
  #      y: 64
  #      z: 20000
  #    - x: -15000
  #      y: 64
  #      z: -5000
  #  # Use visibilitylimits to restrict which areas of maps on your world to render (zero or more rectangles can be defined)
  #  visibilitylimits:
  #    - x0: -1000
  #      z0: -1000
  #      x1: 1000
  #      z1: 1000
  #    - x0: -2000
  #      z0: -1000
  #      x1: -1000
  #      z1: -500
  #  # Use hidestyle to control how hidden-but-existing chunks are to be rendered (air=empty air (same as ungenerated), stone=a flat stone plain, ocean=a flat ocean)
  #  hidestyle: stone
  #  # Use 'autogenerate-to-visibilitylimits: true' to choose to force the generation of ungenerated chunks while rendering maps on this world, for any chunks within the defined
  #  # visibilitylimits (limits must be set).  The three options here are: none (default - no autogenerate), map-only (temporarily generate chunks for map, but don't save them (no world change),
  #  # permanent (generate and save chunks - this permanently adds the chunks to the world, as if a player had visited them - BE SURE THIS IS WHAT YOU WANT)
  #  autogenerate-to-visibilitylimits: map-only
  #   Use 'template: mycustomtemplate' to use the properties specified in the template 'mycustomtemplate' to this world. Default it is set to the environment-name (normal or nether).
  #  template: mycustomtemplate
  #   Rest of comes from template - uncomment to tailor for world specifically
  #  center:
  #    x: 0
  #    y: 64
  #    z: 0
  #  # If bigworld set to true, use alternate directory layout better suited to large worlds
  #  bigworld: true
  #  # Number of extra zoom-out levels for world (each level is twice as big as the previous one)
  #  extrazoomout: 3
  #  maps:
  #    - class: org.dynmap.hdmap.HDMap
  #      name: flat
  #      title: "Flat"
  #      prefix: flat
  #      perspective: iso_S_90_lowres
  #      shader: default
  #      lighting: default
  #      # To render a world as a "night view", switch to lighting: night
  #      lighting: night
  #      # To render both night and day versions of tiles, set light: nightandday
  #      lighting: nightandday
  #      # Background color for map during the day
  #      backgroundday: "#153E7E"
  #      # Background color for map during the night
  #      backgroundnight: "#000000"        
  #      # Background color for map (independent of night/day)
  #      background: "#000000"
  #    - class: org.dynmap.hdmap.HDMap
  #      name: surface
  #      title: "Surface"
  #      prefix: t
  #      perspective: iso_SE_60_lowres
  #      shader: default
  #      lighting: default
  #      # Add shadows to world (based on top-down shadows from chunk data)
  #      lighting: shadows
  #      # To render a world as a "night view", set lighting: night
  #      lighting: night
  #      # To render both night and day versions of tiles, set lighting: nightandday
  #      lighting: nightandday
  #      # Background color for map during the day
  #      backgroundday: "#153E7E"
  #      # Background color for map during the night
  #      backgroundnight: "#000000"        
  #      # Background color for map (independent of night/day)
  #      background: "#000000"
  #      # Sets the icon to 'images/block_custom.png'
  #      icon: custom
  #      # Biome-based mapping
  #    - class: org.dynmap.hdmap.HDMap
  #      name: biome
  #      title: "Biome"
  #      prefix: b
  #      perspective: iso_SE_60_lowres
  #      lighting: default
  #      # Biome-based shading : biome=biome type, temperature=biome-temperature, rainfall=biome-rainfall
  #      shader: biome
  #    - class: org.dynmap.hdmap.HDMap
  #      name: cave
  #      title: "Cave"
  #      prefix: ct
  #      perspective: iso_SE_60_lowres
  #      shader: cave
  #      lighting: default
  #
  # To just label world, and inherit rest from template, just provide name and title
  #- name: world2
  #  title: "Second World"
  #
  #- name: nether
  #  title: "Nether"
  #  center:
  #    x: 0
  #    y: 64
  #    z: 0
  #  # Number of extra zoom-out levels for world (each level is twice as big as the previous one)
  #  extrazoomout: 3
  #  maps:
  #    - class: org.dynmap.hdmap.HDMap
  #      name: flat
  #      title: "Flat"
  #      prefix: flat
  #      perspective: iso_S_90_lowres
  #      shader: default
  #      lighting: default
  #      # Map background color (day or night)
  #      background: "#300806"
  #    - class: org.dynmap.hdmap.HDMap
  #      name: nether
  #      title: "Surface"
  #      prefix: nt
  #      perspective: iso_SE_60_lowres
  #      shader: default
  #      # Map background color (day or night)
  #      background: "#300806"

# Set to true to enable verbose startup messages - can help with debugging map configuration problems
# Set to false for a much quieter startup log
verbose: true

# Enables debugging.
#debuggers:
#  - class: org.dynmap.debug.LogDebugger
```

Fabian
