### ISSUE TITLE
chatname URl Parameters dosen't work

### ISSUE THREAD

**Issue by rsp4jack** [webbukkit/dynmap#2893]
Excuse my English is not very good.
Examples:
My dynmap URl is http://some.examples.com:8143, I want use chat name "Human", so my URl is http://some.examples.com:8143?chatname=Human
This URl can open dynmap web, but, when i chat in dynmap web, it chat name is "web-001"
What i doing wrong? How i to fixed this bug?
Config:
```
components:
  - class: org.dynmap.InternalClientUpdateComponent
    hidewebchatip: true
    trustclientname: true`
  - class: org.dynmap.SimpleWebChatComponent
    allowchat: true
    allowurlname: true
  - class: org.dynmap.ClientComponent
    type: chat
    allowurlname: true
```
//Chinese
举个例子，我的dynmap网址是http://some.examples.com:8143
我想用“Human”这个聊天名称，所以我把URl改成http://some.examples.com:8143?chatname=Human
这个网址能打开dynmap界面，但是，聊天名称却是”web-001“，为什么聊天名称不是“Human”？相应的配置也都正确。具体配置请看上方英文版本。
