### ISSUE TITLE
Connection issue with mysql?

### ISSUE THREAD

**Issue by johnsoncui02** [webbukkit/dynmap#2986]
https://pastebin.com/xqJcwSYv

**Comment by Kimax89** [comment]
In configuration.txt

Do you have `flags: "?allowReconnect=true"` under your storage settings?

Example:

```
storage:
  type: mysql
  hostname: localhost
  port: 3306
  database: dynmap
  userid: dynmap-user
  password: dynmap-password
  prefix: ""
  flags: "?allowReconnect=true"
```
