### ISSUE TITLE
Missing dynmap_config.php when using SQLite config and "Web files are not matched with plugin version: All files need to be same version (undefined)"

### ISSUE THREAD

**Issue by JappeHallunken** [webbukkit/dynmap#3680]
**Issue Description:** 
Hello, 
I used the wiki to configure Dynmap for using SQLite with an external webserver (Lighttpd).
When I go to the webpanel, I got the error:
*Web files are not matched with plugin version: All files need to be same version (undefined)*
But everything works with MariaDB or the config for using tiles, so it's not a permission issue, nor browser cache related or other stuff, I tried really everything.

So I looked into my error.log of Lighttpd and found this:

```
2022-02-15 19:04:58: mod_fastcgi.c.487) FastCGI-stderr:PHP message: PHP Warning:  file(dynmap_config.php): failed to open stream: No such file or directory in /var/www/dynmap/standalone/configuration.php on line 20

PHP message: PHP Warning:  array_shift() expects parameter 1 to be array, bool given in /var/www/dynmap/standalone/configuration.php on line 21

PHP message: PHP Warning:  array_pop() expects parameter 1 to be array, bool given in /var/www/dynmap/standalone/configuration.php on line 22

PHP message: PHP Warning:  implode(): Invalid arguments passed in /var/www/dynmap/standalone/configuration.php on line 23

PHP message: PHP Notice:  Trying to get property 'loginrequired' of non-object in /var/www/dynmap/standalone/configuration.php on line 27

PHP message: PHP Warning:  Creating default object from empty value in /var/www/dynmap/standalone/configuration.php on line 31

PHP message: PHP Notice:  Undefined property: stdClass::$worlds in /var/www/dynmap/standalone/configuration.php on line 32

PHP message: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/dynmap/standalone/configuration.php on line 32

PHP message: PHP Notice:  Undefined variable: newworlds in /var/www/dynmap/standalone/configuration.php on line 6
```

And indeed, there is no `dynmap_config.php` in the standalone/ folder generated, when first launching the server with Dynmap plugin.
Idk if this missing file is causing the error in the webpanel? But something is really odd whit the SQLite config or maybe even the how-to in this wiki? I couldn't figure out what is causing the error.

* **Dynmap Version:** *Dynmap-3.3.2-696*
* **Server Version:** *PaperMC 1.18.1-198*
* **Pastebin of Configuration.txt:** *I used the config mentioned [*here](https://github.com/webbukkit/dynmap/issues/2609)*
* **Server Host (if applicable):** *My Raspberry Pi 4 running with DietPi*
* **Steps to Replicate:** *Use the How-To from this wiki for running SQLite with deactivated internal webserver*

 [ x] *I have looked at all other issues and this is not a duplicate*  
 [ x] *I have been able to replicate this*

**Comment by JappeHallunken** [comment]
I figuered it out by myself, bc the linked tutorial and the wiki is a bit misleading.
This is valid url config in `configuration.txt` for using SQLite and external webserver:

```
storage:
  #type: filetree
  # SQLite db for map storage (uses dbfile as storage location)
   type: sqlite
   dbfile: dynmap.db

...

url:
    # configuration URL
    configuration: "standalone/dynmap_config.json?={timestamp}"
    # update URL
    update: "standalone/dynmap{world}.json?_={timestamp}"
    # sendmessage URL
    sendmessage: "standalone/sendmessage.php"
    # login URL
    login: "standalone/login.php"
    # register URL
    register: "standalone/register.php"
    # tiles base URL
    tiles: "standalone/SQLite_tiles.php?tile="
    # markers base URL
    markers: "standalone/SQLite_markers.php?marker="
```
Don't forget to comment the other stuff mentioned [here](https://github.com/webbukkit/dynmap/wiki/External-Webserver-Basics)
