### ISSUE TITLE
Remove superfluous rendering ???

### ISSUE THREAD

**Issue by Blueeyestar** [webbukkit/dynmap#3737]
Good day,
we have a problem with our map.
Whenever we render, there are errors on the map.
It renders further than it should.
The whole map is almost round except in one place.
We now want to remove the section that has been rendered superfluous.
Now we have the problem that we cannot exactly assign which image is intended for which position in order to remove the images precisely.
Is there a possibility to assign your picture to a position based on the exact coordinates?

Or is there another way to fix it

![map1](https://user-images.githubusercontent.com/35557302/162611589-735f4182-5b56-4aa0-a311-f7c6f67ab896.png)

![map2](https://user-images.githubusercontent.com/35557302/162611597-54c38320-fa4c-42be-ba3f-ee6383e68fb0.png)

**Comment by JurgenKuyper** [comment]
what you are asking is not easily possible, however, there is a workaround. you can add a circular visibilitylimit in worlds.txt:
```yaml
    visibilitylimits:
      - x: -2000
        z: -1000
        r: 200
    hidestyle: air
```
what is stated above will render everything in range of the circle with radius of 200 and centered around x:-2000,z:-1000.
after a restart and a radiusrender in the problematic part it should be black (hidestyle: air)

**Comment by Blueeyestar** [comment]
> what you are asking is not easily possible, however, there is a workaround. you can add a circular visibilitylimit in worlds.txt:
> 
> ```yaml
>     visibilitylimits:
>       - x: -2000
>         z: -1000
>         r: 200
>     hidestyle: air
> ```
> 
> what is stated above will render everything in range of the circle with radius of 200 and centered around x:-2000,z:-1000. after a restart and a radiusrender in the problematic part it should be black (hidestyle: air)

where do you get the coordinates from
 x: -2000
 z: -1000

**Comment by JurgenKuyper** [comment]
> where do you get the coordinates from x: -2000 z: -1000

from the default worlds.txt. most often it is the spawn if not defined during pregeneration

**Comment by Blueeyestar** [comment]
> > where do you get the coordinates from x: -2000 z: -1000
> 
> from the default worlds.txt. most often it is the spawn if not defined during pregeneration

```
worlds:
-   name: world
    title: world
    enabled: true
    protected: false
    showborder: true
    sendposition: true
    sendhealth: true
    extrazoomout: 2
    visibilitylimits:[]   
    hiddenlimits: [
        ]
    hidestyle: stone
    maps:
    -   class: org.dynmap.hdmap.HDMap
        name: flat
        title: Flat
        prefix: flat
        perspective: iso_S_90_lowres
        shader: stdtexture
        lighting: shadows
        image-format: default
        mapzoomin: 1
        mapzoomout: 3
        boostzoom: 0
        tilescale: 0
        append_to_world: ''
        protected: false
    -   class: org.dynmap.hdmap.HDMap
        name: surface
        title: Surface
        prefix: t
        perspective: iso_SE_30_hires
        shader: stdtexture
        lighting: shadows
        image-format: default
        mapzoomin: 1
        mapzoomout: 5
        boostzoom: 0
        tilescale: 0
        append_to_world: ''
        protected: false
```
I'm acting a bit stupid right now...trying to understand what the x and z coordinates are
