### ISSUE TITLE
Tiles dont render under Overhangs

### ISSUE THREAD

**Issue by Aaron2550** [webbukkit/dynmap#3750]
**Issue Description:** Tiles under overhangs dont render if the blocks underneath arent lit

* **Dynmap Version:** 3.4 Beta-3-774
* **Server Version:** Paper Build 317 for 1.18.2
* **Server Host (if applicable):** Selfhosted
* **Other Relevant Data/Screenshots:** See below
* **Steps to Replicate:** Have Overhang in world, have it be unlit, see problem.

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

Custom Perspective:
```
perspectives:
  - class: org.dynmap.hdmap.IsoHDPerspective 
    name: iso_idunno_SE_60_i_guess_very_hires
    azimuth: 135
    inclination: 60
    scale: 32
```

Screenshots:
![image](https://user-images.githubusercontent.com/24834067/166261314-4858686e-aa3c-45d0-87ec-725d37c54ac4.png)
![image](https://user-images.githubusercontent.com/24834067/166261624-79467f95-105a-468c-855c-39483f8736f9.png)
![image](https://user-images.githubusercontent.com/24834067/166262766-4296b0f3-69f6-4fb7-b4a5-85edff921578.png)
