### ISSUE TITLE
Visibility Limits Not Working

### ISSUE THREAD

**Issue by ImBonana** [webbukkit/dynmap#3802]
This is my worlds.txt
```
worlds:
-   name: world
    title: World
    enabled: true
    protected: false
    showborder: true
    sendposition: true
    sendhealth: false
    extrazoomout: 2
    visibilitylimits:
    -   x0: -24575
        z0: -12287
        x1: 24575
        z1: 12287
    hiddenlimits: [
        ]
    hidestyle: air
    maps:
    -   class: org.dynmap.hdmap.HDMap
        name: flat
        title: Flat
        prefix: flat
        perspective: iso_S_90_lowres
        shader: stdtexture
        lighting: shadows
        image-format: default
        mapzoomin: 1
        mapzoomout: 3
        boostzoom: 0
        tilescale: 0
        append_to_world: ''
        protected: false
    -   class: org.dynmap.hdmap.HDMap
        name: surface
        title: Surface
        prefix: t
        perspective: iso_SE_30_hires
        shader: stdtexture
        lighting: shadows
        image-format: default
        mapzoomin: 1
        mapzoomout: 5
        boostzoom: 0
        tilescale: 0
        append_to_world: ''
        protected: false
-   name: world_nether
    title: world_nether
    enabled: true
    extrazoomout: 2
    maps:
    -   class: org.dynmap.hdmap.HDMap
        name: flat
        title: Flat
        prefix: flat
        perspective: iso_S_90_lowres
        shader: stdtexture
        lighting: nethershadows
        background: '#300806'
        mapzoomin: 1
    -   class: org.dynmap.hdmap.HDMap
        name: nether
        title: Surface
        prefix: nt
        perspective: iso_SE_30_hires
        shader: stdtexture
        lighting: nethershadows
        background: '#300806'
        mapzoomin: 1
-   name: world_the_end
    title: world_the_end
    enabled: true
    extrazoomout: 2
    maps:
    -   class: org.dynmap.hdmap.HDMap
        name: flat
        title: Flat
        prefix: flat
        perspective: iso_S_90_lowres
        shader: stdtexture
        lighting: brightnight
        mapzoomin: 1
    -   class: org.dynmap.hdmap.HDMap
        name: the_end
        title: Surface
        prefix: st
        perspective: iso_SE_30_hires
        shader: stdtexture
        lighting: brightnight
        mapzoomin: 1
```
