### ISSUE TITLE
Allow Multiple Renders (with different settings of the same world)

### ISSUE THREAD

**Issue by SkyLicks** [webbukkit/dynmap#3835]
> template is **bold**
> sample data is *italicized*

**Feature Description:**

The basic feature I am requesting is to allow us to create multiple renders of the same world. So in the worlds.txt, the configuration would go like this:

```
worlds:
  - id: world_1
    world: world
   visibilitylimits:
      - x0: 1163
        z0: 767
        x1: -1269
        z1: -690
  ...
  - id: world_2
    world: world
   visibilitylimits:
      - x0: 4000
        z0: 9000
        x1: 2000
        z1: 7000
  ...
```

* **Additional context:** 

The basic problem I'm trying to solve are:
* Its not possible to disable certain markers in certain views. For example, if there is a POI in a cave and you add a marker for it, then that marker would also show in the "above ground" views. This is not ideal. By being able to render the and world multiple times as if it was another world, you can sort of circumnavigate this issue (though a direct fix would also be nice) 
* OK, so I have a minigame server. We have a spawn there and the main map. I want to render the spawn and the main map (all in the same world) separately. Because everything in between is just void for all intents and purposes. For all anyone cares, the spawn and the main map might as well be in separate worlds.
