### ISSUE TITLE
infinite loop of S3 list requests

### ISSUE THREAD

**Issue by fosscel** [webbukkit/dynmap#4217]
**Issue Description:** When processing map tiles, an infinite loop of listing objects can be encountered.

* **Dynmap Version:** v3.0+ (since #3689)
* **Server Version:** all versions
* **Other Relevant Data/Screenshots:** 
here is a screenshot illustrating the phenomenon, with `GET` requests to minio in red, and other request methods in green:
![Image](https://github.com/user-attachments/assets/de94e05d-794b-41ff-92fd-edd5bca90889)
the switch from green to red coincides with the timing of the `Full render of maps... completed` message being displayed.

this bug occurs because of the use of [`getContinuationToken()`](https://github.com/webbukkit/dynmap/blob/3abbca8582eef65a063f99a9dbf474d49e77087f/DynmapCore/src/main/java/org/dynmap/storage/aws_s3/AWSS3MapStorage.java#L410C77-L410C95) rather than `getNextContinuationToken()` (AWS [documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html#API_ListObjectsV2_ResponseSyntax))

* **Steps to Replicate:**

configure dynmap to use s3, and add a custom template suffix:
```
deftemplatesuffix: testing
```
and the `normal-testing.txt` to reproduce this:
```
version: 0.20
templates:
  normal-testing:
    enabled: true
    extrazoomout: 0
    maps:
      - class: org.dynmap.hdmap.HDMap
        name: e90
        title: "e90"
        prefix: e90
        perspective: iso_E_90_vlowres
        shader: stdtexture
        lighting: default
        mapzoomin: 0
      - class: org.dynmap.hdmap.HDMap
        name: s90
        title: "s90"
        prefix: s90
        perspective: iso_S_90_vlowres
        shader: stdtexture
        lighting: default
        mapzoomin: 0
```
after running `/dynmap fullrender`, the `e90` render will complete, and then the `s90` render will not begin.

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*
