### ISSUE TITLE
coord box is too small for 4-digit coords

### ISSUE THREAD

**Issue by superjamie** [webbukkit/dynmap#639]
The box that displays the map co-ordinates is too small when handling 4 digit map co-ordinates.

A coordinate like **-2000,64,-2000** gets cut off due to the size of the coord box and becomes **-2000,64,-20**

The following in `/web/css/dynmap_style.css` makes it better. I think most people are probably using a map somewhere between 1000 and 9999 coords large. Please consider making this the default?

``` css
.dynmap .coord-control {
        width: 100px;
}

.dynmap .coord-control-noy {
        width: 100px;
}
```

If someone has 5 digit co-ords (eg: **-10000**) they'll still get cut off but I'm not smart enough to write a dynamically resizing box. You might not want that anyway.
